#!/usr/bin/env lua

print(require("common-constants")("CONKY_NAME"))

local dbus = require("dbus-common")

print(arg[1])

local emit, _
if arg[1] == "as-conky" then
    _, emit, _ = dbus("conky")
elseif arg[1] == "as-awesome" then
    _, emit = dbus("awesome")
else
    io.stderr:write("first arg must be 'as-conky' or 'as-awesome'\n")
    os.exit(1)
end

for i=2, #arg do
    emit(arg[i])
end
