#!/usr/bin/env lua

rawset(_G, "CONKY_DEBUG", true)

local listen, send = require("dbus-common")("awesome")

send(arg[1] or "CPU: ${cpu} RAM: ${mem}")

while true do
    local msg = listen()
    if msg then print(msg) end
end
