#!/usr/bin/env bash

dir=$(dirname $(realpath $0))

conky_iface=$(LUA_PATH="$dir/?.lua;$LUA_PATH" \
  lua -e 'c=require("common-constants"); print(c("STRING_FOR_CONKY"))')

echo "conky interface: $conky_iface"

awesome-client <<EOS

local dbus = dbus
dbus.emit_signal("session",
                 "/",
                 "$conky_iface",
                 "Conky",
                 "string",
                 "$1")
EOS
